version: "3.9"

services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "5173:80"
    networks:
      - todo-network
    depends_on:
      - backend

networks:
  todo-network:
    driver: bridge
