spring:
  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb # <- Cambiado a mem
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create # <- Cambiado a create para recrear siempre